### ISSUE TITLE
Upload not minified backbone and jquery.

### ISSUE THREAD

**Issue by psande** [thomasdavis/backboneboilerplate#10]
I really want to know how you managed to get backbone and jquery working as a module.
So far, I've only found how to do it including JQuery in the same file as Require.js.

Thanks.

**Comment by thomasdavis** [comment]
Hey, if you check out main.js you can see the link to the AMD managed repos https://github.com/amdjs

**Comment by psande** [comment]
Oh, I see... Sorry for the trouble, I missed that.

I just found a StackOverflow question that mentions your code.

BTW, thanks for your work.

**Comment by thomasdavis** [comment]
lol no problem, are they mentioning the boilerplate code or older?

No problem, I should really push more stuff

**Comment by psande** [comment]
The boilerplate. I just lost the link, I'll let you know where if I find it.

Yep, the examples and the boilerplate are right, but the code is a bit messy, there are some useless files, and what is more of a backdraw is that some files are minified. It just doesn't make sense for development and you can use r.js later.

I cleaned up the entire project, added some libraries, multiple routers, twitter bootstrap and refactored the project to a new folder structure that I think it is more adequate.

I'll fork your project tomorrow, make the changes and make a push request so you can check if you like the changes.

**Comment by thomasdavis** [comment]
Sounds pretty good, if you could put the changes on a branch that would be fantastic.  That way other developers can try it out before it's merged into master.

Look forward to seeing them
