### ISSUE TITLE
Prevent zombie view in router.js

### ISSUE THREAD

**Issue by thomasdao** [thomasdavis/backboneboilerplate#11]
Hi,

Thanks for creating the boilerplate, I really like it. This is just minor suggestion to prevent zombie view in the file router.js

Currently we always create a new view when user navigate to different url, and never close or reuse them properly.

E.g: 
    optimize: function () {
      require(['views/optimize/page'], function (OptimizePage) {
        var optimizePage = new OptimizePage();
        optimizePage.render();
      });
    },

I think a better approach is to check whether the page is already been initialized, then we can reuse it efficiently without creating new page every time. For e.g:

if (! this.optimizePage) {
    this.optimizePage = new OptimizePage()
}
this.optimizePage.render()

**Comment by thomasdavis** [comment]
Thanks Thomas, you are exactly right.  I am working on the View Manager write now that controls the life cycle of views and stops zombie views, will be pushing in the next few hours. Thanks again!

**Comment by thomasdao** [comment]
Hi,

I think it would be a nice improvement when we return 'this' on the render method. 

ChildPage = Backbone.View.extend {
render: function() {
// do something
return this;
}
}

Sometime, from master page we want to append a child page, we could do:
childPage = new ChildPage()
$(element).append(childPage.render().el)

**Comment by engram-design** [comment]
I've also had issues with the current View Manager, which, while great, doesn't clean up properly. I came across this after loading views where events defined in (events.js) were being triggered multiple times. To work around this, I'm using undelegateEvents() on the previous view before creating a new one.

I'm aware that the VM isn't fully implemented yet, but any plans on setting this up?

**Comment by thomasdavis** [comment]
on second thought undelegateEvents is probably the only default cleanup a view manager should do and also calling clean() if it has been defined. What do you think?

**Comment by engram-design** [comment]
I'm certainly no expert, but that's just what I'm doing! Sounds good :)

Also, on the subject of VM - is it supposed to re-use already created views when called again? As currently, it doesn't seem to, and just creates a new view when create is called. In fact, views[name] is never defined.

Thanks for your quick response by the way!

**Comment by thomasdavis** [comment]
So in the view manager the views should always be created fresh, if you want to maintain a view you can do so using your applications logic.

Some goals I had for the view manager were 
- clean up !important
- managing children / nested views
- a basic signalling of view creation to the app 
- eventually more advanced event delegation e.g. the ability to make all event listeners on a view dormant etc
- handle dynamic reusable views such as table rows

For now I've changed the unbind() to undelegateEvents().

**Comment by engram-design** [comment]
Ok, that clears that up - sounds good. Thanks mate!
