### ISSUE TITLE
Missing require/order plugin?

### ISSUE THREAD

**Issue by tcrosen** [thomasdavis/backboneboilerplate#12]
I see the **text** plugin is there but not **order**.

**Comment by thomasdavis** [comment]
At the moment the boilerplate just expects you to wrap third party
libraries in AMD wrappers which can automatically be done using volojs
amdify if you desire.

I would prefer to keep boilerplate strictly AMD as an attempt to force
developers to AMDify all the third parties libraries that currently exist.

On Thu, Mar 22, 2012 at 3:59 AM, Terry Rosen <
reply@reply.github.com

**Comment by tcrosen** [comment]
Was asking because you included it in the sample but the file doesn't exist

```
// Require.js plugins
text: 'libs/require/text',
order: 'libs/require/order',
```

**Comment by thomasdavis** [comment]
My bad, will probably remove it, what are your thoughts on mixing synchronous with non-sync scripts

**Comment by tcrosen** [comment]
In what sense?  In the same boilerplate?  I actually stumbled on your project because I'm creating myself a boilerplate server-side MVC project with Backbone.js handling the front-end and I liked your approach.

**Comment by tyaakow** [comment]
You people with backbone/require.js examples available online, have made all your examples as complicated as complicated gets.
I might just load jquery, backbone and underscore + 2-3 my own files, without this spaghetti

**Comment by tyaakow** [comment]
Your backbone book also has order script in all examples, and in actual files there is none.
By the time I figure your examples, I may as well build me a project.
