### ISSUE TITLE
layout page not loading before routes

### ISSUE THREAD

**Issue by engram-design** [thomasdavis/backboneboilerplate#13]
Firstly, great work on this boilerplate! I've been following your backbonetutorials.com tutorials, and combined with this, has really helped in understanding backbone.js (this is the 3rd time i've tried to learn it).

Just wondering where the best place to include a login check would be? Would it be in the main.js file, or inside the app.js? The code for that isn't the issue, as its fairly straightforward, however, the way i've done it seems to be cause issues.

In app.js, code checks for previous user login (using API call). If logged in, render the app template (layout.html), otherwise render the login template. This is working fine, however, if a route is set (say /dashboard) on page load, the the app template will be too slow to load, and the dashboard template cannot attach itself to the DOM node in layout.html (doesn't exist yet). This is especally evident as sometimes it'll be fine, but others it will not appear.

So, it's ovbiously the extra API call that is causing the main layout to be too slow. Is there a way we can activate the routes only when the layout.html file is loaded and ready?

Happy to push some code up if that would help!

**Comment by thomasdavis** [comment]
Thanks for the kind words, heading to bed in a moment but will make session.js my highest priority for tomorrow.

It will most likely be a Backbone.Model and be included in app.js. 

This is some much older code https://github.com/thomasdavis/apitime/blob/gh-pages/js/session.js

But I have a much better idea of how to do it now and look forward to sharing it tomorrow

**Comment by engram-design** [comment]
No worries! I'll get started with the old session.js file - at least thats a good starting point.

Look forward to seeing the updated version of it!

**Comment by engram-design** [comment]
So, I've got a semi working example using sessions.js, but just wondering about the best way to pass it along to all the other modules in the app? Ideally, I'd create a session.js Model at app initialize, and then use that instance to store the users logged in state. How can this be called (or passed) to other views without creating a new Model?

**Comment by engram-design** [comment]
If anyone is interested, a great post on setting up a session.js can be found here http://blog.opperator.com/post/15671431847/backbone-js-sessions-and-authentication

**Comment by thomasdavis** [comment]
can't seem to PM you @engram-design

**Comment by engram-design** [comment]
Do I need to enable something? Feel free to email me @thomasdavis
