### ISSUE TITLE
backbone 0.9.2 not working with this example

### ISSUE THREAD

**Issue by nuweb** [thomasdavis/backboneboilerplate#14]
Getting Backbone is null error in Firebug. Please suggest, thanks!

**Comment by thomasdavis** [comment]
Will look into this asap, if you figure it out before I get to it, feel free to share.

**Comment by nuweb** [comment]
Sure thanks! 
I haven't tried this, but worth looking at, https://github.com/addyosmani/backbone-fundamentals/issues/60

**Comment by thomasdavis** [comment]
I actually thought about it while I was drunk last night, this boilerplate using AMD versions of libraries from

http://github.com/amdjs <- Get the latest backbone from here and you should be in the clear

**Comment by nuweb** [comment]
Thank you, really appreciate!
