### ISSUE TITLE
events.js usage

### ISSUE THREAD

**Issue by engram-design** [thomasdavis/backboneboilerplate#15]
Quick question (sorry about raising an issue) - what is the events.js used for in the backbone boilerplate? Is this where we can create modular events, which we can re-use elsewhere in the app?

If so, how can we use it?

**Comment by thomasdavis** [comment]
Hey man, was still fleshing it out...

You are correct, modules should be able to broadcast and listen to events.   This allows for decoupled modules and facilitates a more robust communication model  between entities.

Module A might broadcast an event on a channel such as 'message received'.

Module B (chat pane) and Module C (UI notification) bind themselves to the same channel and can act accordingly.

At the moment in the boilerplate, vm.js throws a message into the event bus that says a new view is created.

The footer.js containing the graph is bound to listen on that channel and re-render when new view events are broadcasted.

**Comment by engram-design** [comment]
No worries at all - just came across the need for using it in my project, and thought that might be what it was used for! Nice work! :)
