### ISSUE TITLE
problem with $.ajax call when overriding Backbone.sync in offline mode

### ISSUE THREAD

**Issue by khoimk** [thomasdavis/backboneboilerplate#19]
I want to have my own way to use $.ajax in sync method. Everything goes right if i don't use manifest file to cache my app for offline use. But when i apply cache the $.ajax call failed. I tried to place the ajax call in other mudule then i worked ok.
Here's my code:
Backbone.sync = function (method, model, options) {
        var resp;
        var store = model.localStorage || model.collection.localStorage;

```
    switch (method) {
        //case "read":    resp = model.id ? store.find(model) : store.findAll(); break;      
        case "read": 
         $.ajax({ 
         cache:false,
         url: model.url, 
         type: 'GET',
         contentType: 'application/json;',
         dataType: 'json', 
         success: function (data) { alert('ok'); },
         error: function(){alert('failed');}
         }); 

        break;
        case "create": resp = store.create(model); break;
        case "update": resp = store.update(model); break;
        case "delete": resp = store.destroy(model); break;
    }
};
```

This code is place in localstorage.js file of the Todos example.
Please help,

**Comment by thomasdavis** [comment]
Have you tried putting that snippet in app.js?

**Comment by khoimk** [comment]
Thank for reply. I have put this in app.js. When i call foodList.fetch() this problem still happens
define([
        'jquery',
        'underscore',
        'backbone',
        'libs/misc/loader'
    ], function ($, _, Backbone, Loader) {
    var appView = Backbone.View.extend({
            loader : new Loader(10000),
            initialize : function () {
                var appCache = window.applicationCache;
                appCache.onupdateready = function (e) {
                    if (window.applicationCache.status == window.applicationCache.UPDATEREADY) {
                        try {
                            window.applicationCache.swapCache();
                            if (confirm('new version, reload?')) {
                                window.location.reload();
                            }
                        } catch (err) {}
                    }
                }
                Backbone.sync = function (method, model, options) {
                    var resp;
                    var store = model.localStorage || model.collection.localStorage;

```
                switch (method) {
                    //case "read":    resp = model.id ? store.find(model) : store.findAll(); break;
                case "read":
                    $.ajax({
                    cache:false,
                    url: model.url,
                    type: 'GET',
                    contentType: 'application/json;',
                    dataType: 'json',
                    success: function (data) { alert(data); },
                    error: function(e){alert(e);}
                    });

                    break;
                    // case "create": resp = store.create(model); break;
                case "update":
                    resp = store.update(model);
                    break;
                case "delete":
                    resp = store.destroy(model);
                    break;
                }

                // if (resp) {
                // options.success(resp);
                // } else {
                // options.error("Record not found");
                // }
            }
            this.loader.initialize();
        },

        render : function () {
            //menubar
            require([
                    'views/home/menu'], function (view) {
                require(['collections/hobbies'], function (Hobbies) {
                    //view.model = Hobbies;
                    view.render();
                })
            });
        }
    });
return new appView;
```

});

Here's the network log from Chrome:

GetFoodList
/bbex/Home
GET
(failed)
application/json;
jquery-min.js:4
Script
13B
0B
884ms
0.0 days

**Comment by thomasdavis** [comment]
Could you post what error your getting?

**Comment by khoimk** [comment]
You can see the chrome network log here: 
http://s7.postimage.org/lkfmg4057/error.png

GetFoodList
/bbex/Home
GET
(failed)
application/json;
jquery-min.js:4
Script
13B
0B
884ms
0.0 days

**Comment by thomasdavis** [comment]
Click on that network request for more details and screenshot that to please

**Comment by khoimk** [comment]
http://s13.postimage.org/w1geq87zb/er1.png

**Comment by thomasdavis** [comment]
I think it has more to do with your server, is it on the same domain?

**Comment by khoimk** [comment]
Yes, it runs on the same domain. This ajax call works fine in other module except in Backbone.sync. I have removed the manifest="app.appcache" in html tag then it works fine but I coundn't use app in offline mode. Maybe is sth in conflict with jQuery?

**Comment by khoimk** [comment]
I have published my app here: http://apps.ditoi.com/index.html
Please choose link: Shop
At the first load, the ajax call (GetFoodList) runs ok but when you hit F5 the ajax call will fire error. If you del Chrome's cache and it will run ok.
Please help me find the solution. 
Thanks.

**Comment by thomasdavis** [comment]
Works for me, which browser are you using?

**Comment by khoimk** [comment]
Both FF and Chrome get this error. I recorded a clip.
The first, after clear all Chrome cache, the ajax call was fine. And the second, when i clicked refresh button the call got error.
http://youtu.be/-_rSQN50nr4

**Comment by khoimk** [comment]
After many hours testing, I think there's a problem when using Backbone.sync with offline mode of HTML5. Although I used the Backbone.sync of fw without modifying, this error still occurred when using manifest to cache the app. You can see how I reproduce the bug in this video: http://www.youtube.com/watch?v=4ksH2tLZwdg
Please let me know whether it's a bug or not.
Many thanks.
