### ISSUE TITLE
Use Lo-Dash instead of Underscore.js.

### ISSUE THREAD

**Issue by jdalton** [thomasdavis/backboneboilerplate#23]
Lo-Dash is a drop-in replacement for Underscore.js, from the devs behind [jsPerf.com](http://jsperf.com), that delivers [performance improvements](http://lodash.com/benchmarks), [bug fixes](https://github.com/bestiejs/lodash#closed-underscorejs-issues), and [additional features](https://github.com/bestiejs/lodash#features).

It has a [Backbone build](http://lodash.com/#custom-builds) and is supported by other Backbone boilerplates ([here](https://github.com/gfranko/Backbone-Require-Boilerplate) and [here](https://github.com/tbranyen/backbone-boilerplate)).

**Comment by traviskaufman** [comment]
:+1:

**Comment by thomasdavis** [comment]
Merged in, lodash ftw!

**Comment by shanimal** [comment]
Why does the backbone boilerplate contain paths to lodash and underscore. Would this load both libraries?

Usually in my require.config... 

`require.config({paths : {'underscore' : "_lib/lodash/v1.0.0-rc3/lodash-min"})`

In my main.js I changed the underscore path to `underscore: 'libs/lodash/lodash'` and I don't see any errors.

**Comment by shanimal** [comment]
Sorry. Nix that. It complains. Damn you browser cache!

Is this a special underscore-less lodash build?
