### ISSUE TITLE
Does not work with newest version of backbone.js(0.9.2)

### ISSUE THREAD

**Issue by dva00jnd** [thomasdavis/backboneboilerplate#30]
Tried to add newest require.js and add shim, then it loaded but seems like no routing/events etc works.(Will look into it, later)
require.config({ 
    'paths': { 
    "underscore": "libs/underscore-min", 
        "backbone": "libs/backbone-min"
    },
    'shim': 
    {
        backbone: {
            'deps': ['jquery', 'underscore'],
            'exports': 'Backbone'
        }
    }  
});

**Comment by thomasdavis** [comment]
Had to update routes to not use forward slash, fixed now and updated backbone to 9.2
