### ISSUE TITLE
mac osx - build.sh fails

### ISSUE THREAD

**Issue by ghost** [thomasdavis/backboneboilerplate#6]
the build.sh script fails on mac os x due to the -i flag needing a mandatory extension argument. Here's the fix:

sed -i "" 's/js\/l......

cheers. awesome work.

**Comment by thomasdavis** [comment]
Excellent, I will get on fixing it. Curious as to how you find the build process, do you like the output structure? Is it intuitive etc

**Comment by ghost** [comment]
I'm reviewing it today in fact. I'm building a test app using your framework. I'll let you know how it goes.

Michael

**Comment by thomasdavis** [comment]
Awesome, it would be a stretch calling it a framework but definitely usable as a base.   I am trying to flesh it out as fast as possible and can get onto implementing any questions you have quite fast.

**Comment by bbguitar** [comment]
The Fix is quite easy... update build.sh and change the sed line to

sed -i  bk 's/js\/libs\/require\/require.js/http:\/\/requirejs.org\/docs\/release\/1.0.5\/minified\/require.js/g' output/index.html

Osx's -i option to sed seems to require an extension to use as a backup file.

Kind regards, Spencer

**Comment by ghost** [comment]
thanks. 

after spending a couple of days building on this boilerplate, the only change I would make is to use the default express directory structure at the top level, and use the default express routing. By placing all of the the directories in /public, you can have a single route in routes/index.js:

exports.index = function(req, res){
  res.redirect('/index.html');
};

then you can directly access the build output using /build/output/index.html, so both the test and the build are available.

deploying then is just a matter of copying build/output to /public on your production system.

I've also built a loading diagram to help understand how the loading sequence/dependencies work. I can send it to you if you'd like. That way you can create an images directory in the css directory also.

Michael

**Comment by thomasdavis** [comment]
Hey Michael, great tips for the dev server and I will copy that fix in, had problems running it on Ubuntu but will figure something out. I'm very curious to see the loading diagram!

**Comment by okor** [comment]
Recommended fix was integrated.
