### ISSUE TITLE
Globals for jQuery, Backbone, and _.

### ISSUE THREAD

**Issue by twalker** [thomasdavis/backboneboilerplate#9]
Great boilerplate, thank you.

Although it appears the major libs (jquery, underscore, backbone) are using the AMD wrapped versions, yet they're still defined as globals. 
window.jQuery, window.Backbone, and  window._ are available on both the unbuilt and built versions of the boilerplate.

Is this intended? If not, it'd be splendid if they were not globals and only defined as AMD modules.

**Comment by thomasdavis** [comment]
hey @twalker, thanks for opening this issue I didn't realize that they were global.  They should be by default but obviously not so I will look into it

**Comment by thomasdavis** [comment]
The libraries are doing this by default unfortunately, you would have to wrap the library.
